### ISSUE TITLE
anomaly score

### ISSUE THREAD

**Issue by mahdisn76** [msimms/LibIsolationForest#4]
Hi,
I'm using C++.
My question is, what is the return value of Score function? how can I detect a sample is anomaly or not based on the Score return value?
Thank you in advance.

**Comment by mahdisn76** [comment]
in the original paper by the algorithm's creator it is quoted that:

> Using the anomaly score s, we are able to make the following assessment: 
• (a) if instances return s very close to 1, then they are deﬁnitely anomalies, 
• (b) if instances have s much smaller than 0.5, then they are quite safe to be regarded as normal instances, and 
• (c) if all the instances return s ≈ 0.5, then the entire sample does not really have any distinct anomaly.

so I need something like this.

**Comment by mahdisn76** [comment]
in the original paper by the algorithm's creator it is quoted that:

> Using the anomaly score s, we are able to make the following assessment: 
• (a) if instances return s very close to 1, then they are deﬁnitely anomalies, 
• (b)ifinstanceshavesmuchsmallerthan0.5,thenthey are quite safe to be regarded as normal instances, and 
• (c) if all the instances return s ≈ 0.5, then the entire sample does not really have any distinct anomaly.

so I need something like this.

**Comment by msimms** [comment]
I need to add this. Right now it's just returning the average path length.

**Comment by mahdisn76** [comment]
So now it is not possible to detect whether a data is normal or it is abnormal?
if it is not, when do you think you can add this feature?

**Comment by msimms** [comment]
Right now, you'd have to draw an arbitrary line based on the path length. However, I can probably add this in the next few days.

**Comment by mahdisn76** [comment]
Thanks a lot that will be great.
I'm waiting for it.

**Comment by msimms** [comment]
Added a NormalizedScore() method (in python, rust, and cpp).

**Comment by msimms** [comment]
Released in v.1.1 as "NormalizedScore".
